apiVersion: v1
kind: Pod
metadata:
  name: my-flask-app-pod
  labels:
    app: my-flask-app
spec:
  containers:
    - name: my-flask-app-container
      imagePullPolicy: Always
      image: dorraviv/my-flask-app:v1
      ports: 
        - containerPort: 5000
